### ISSUE TITLE
B-tagging weights not filled

### ISSUE THREAD

**Issue by scooperstein** [vhbb/nanoAOD-tools#8]
Although the module is included in the post-processor, the resulting branches in the output tree for the btagging weights ("Jet_btagSF_*") are filled with 0's. I see that when it is passing the value to the tree to fill 

https://github.com/vhbb/nanoAOD-tools/blob/master/python/postprocessing/modules/btv/btagSFProducer.py#L207

It has normal values, but for some reason the final output tree does not have these values stored but rather 0's. @arizzi

**Comment by arizzi** [comment]
should be ok with #9

**Comment by scooperstein** [comment]
indeed this looks fine now, should be okay to close.
